### ISSUE TITLE
Images disappear when i refresh

### ISSUE THREAD

**Issue by amartini** [andrasferenczi/vitrina#4] opened 2020-08-16 03:43 UTC
Hey man, thanks so much for this extension, I really love it. There's an issue though: every time i manually refresh all images are deleted. I'm not sure how to solve it, or if it's intended behavior, but i think it shouldn't remove images that aren't too old. If you refresh two times in a row all images are gone.
Thanks again,

**Comment by andrasferenczi** [comment] 2020-08-16 05:14
The intended behavior is that `Vitrina` removes all images except for the last one that exists in the gallery of `Muzei`. Refreshing two times means you are possibly loading all the available images fitting your criteria. If you have just a couple subreddits selected, there will be no more to choose from.

I've just ran a test and I got a single image in the `browse` section, which seems to be the intended behavior.

If something is not clear or you see something else, please leave a comment.

**Comment by amartini** [comment] 2020-08-16 13:32
I understand, that's what happens (only one is left). But I believe sometimes I refresh and I don't see images better than the one I was using, but now that one's gone. So maybe remove only when there's over X images or so? Or leave the last X, instead of the last 1 image. Or allow images newer than X time to be reloaded.
Once again thanks for your work.

**Comment by andrasferenczi** [comment] 2020-08-16 13:45
Thanks for you feedback. Keeping the last `X` images is a good idea, issue is that would be more difficult to implement. I'll think about it.

**Comment by amartini** [comment] 2020-08-17 17:15
What if you just remove this line: `.filter { it.id !in existingPostIds }` from `RetrieveLatestImagesUseCase.kt`. It still will only take the last 15, but don't ignore the images already loaded.

**Comment by andrasferenczi** [comment] 2020-08-17 18:13
That would mean you would never receive new images unless the earlier ones are no longer featured on Reddit. Deleting that line would make the image history useless.

There is only [lastAddedArtwork](https://github.com/andrasferenczi/vitrina/blob/4497aebf7a532305e7cf6419254a0f055826d1b5/app/src/main/java/stoyck/vitrina/muzei/VitrinaArtWorker.kt#L62) in the Muzei API, but retrieving the last `X` artworks would take longer to implement (you need the last ids from the saved posts and the fetch the Muzei data using a ContentProvider).

**Comment by andrasferenczi** [comment] 2020-09-06 06:51
Fixed in #9

**Closed by andrasferenczi** 2020-09-06 06:51 UTC
Labels: enhancement

**Comment by scooterama** [comment] 2020-09-17 12:50
How do you delete the queue now? I wondered why all images are added now and the "imagelibrary" keeps filling and filling. Is there an option to go back to renew all images like it was before?

**Comment by andrasferenczi** [comment] 2020-09-18 17:55
@scooterama you can long press and click delete any image
